{% set name = "pipettor" %}
{% set version = "1.2.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pipettor-{{ version }}.tar.gz
  sha256: cfc7fe2119cc8b026132404edb378bb0419437cbde8e6231f251552217e02971

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pipettor
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/diekhans/pipettor
  summary: pipettor - robust, easy to use Unix process pipelines
  doc_url: https://pipettor.readthedocs.io/
  dev_url: https://github.com/diekhans/pipettor
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - diekhans
